#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI " \
	bc="bc -ql" \
	mkdir="mkdir -pv" \
	yt="yt-dlp --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
        ls="lsd --group-dirs first"\
        cat="bat --style=plain"\
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"\
        ip="ip -c"

#misc
alias \
        myip='curl checkip.amazonaws.com'\
        du="du -h"\
	jftui='jftui --no-check-updates'\
	ka='killall -I -w'\
	irssi="irssi --config="$XDG_CONFIG_HOME"/irssi/config --home="$XDG_DATA_HOME"/irssi"\
	yarn='yarn --use-yarnrc "$XDG_CONFIG_HOME/yarn/config"'\
	gitc='/usr/bin/git --git-dir="$HOME/Documents/dotfiles.cfg/" --work-tree="$HOME"'
